// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An account's year, said: what it opened on, what came in and went out -
 * each named by where from or to - what it grew, and what it closed on.
 */
export type AccountFlows = { 
/**
 * The account's display name.
 */
account: string, 
/**
 * Its balance as the year opened.
 */
open: string, 
/**
 * What came in, said.
 */
ins: Array<string>, 
/**
 * What went out, said.
 */
outs: Array<string>, 
/**
 * What came in and then what went out, said.
 */
moves: Array<string>, 
/**
 * What it grew, signed; blank where it did not.
 */
growth: string, 
/**
 * What it grew over what it opened on; blank where it grew nothing or
 * opened empty.
 */
growth_rate: string, 
/**
 * Its balance as the year closed.
 */
close: string, };
