// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An account's year: what it opened on, what came in and went out -
 * each named by where from or to - what it grew, and what it closed on.
 */
export type AccountFlows = { 
/**
 * The account's display name.
 */
account: string, 
/**
 * Its balance as the year opened.
 */
open: number, 
/**
 * What came in, said.
 */
ins: Array<string>, 
/**
 * What went out, said.
 */
outs: Array<string>, 
/**
 * What it grew.
 */
growth: number, 
/**
 * Its balance as the year closed.
 */
close: number, };
