// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";

/**
 * One year's to-dos, as `actions` and `plan_actions` reply.
 */
export type ActionsReply = { 
/**
 * The reported year.
 */
year: number, 
/**
 * Age each person reaches during the year, by person id.
 */
ages: { [key in string]: number }, 
/**
 * Executed instructions in execution order, each tagged by `kind`
 * (`transfer`, `rmd`, `contribution`, `conversion`, `withdrawal`)
 * with account ids and nominal amounts - they are instructions, so
 * no deflated variant exists.
 */
actions: Array<Action>, 
/**
 * Human-readable warnings: unfunded spending, medicare and cliff
 * costs, and the IRMAA surcharge this year's MAGI buys two years out.
 */
warnings: Array<string>, };
