// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContributionNote } from "./ContributionNote";

/**
 * One executed instruction in a projected year, with post-clamp nominal
 * amounts; what a user following the plan would actually do.
 */
export type Action = { "kind": "transfer", 
/**
 * Source account id.
 */
from: string, 
/**
 * Destination account id.
 */
to: string, 
/**
 * Nominal dollars moved.
 */
amount: number, } | { "kind": "rmd", 
/**
 * The distributing account id.
 */
account: string, 
/**
 * Nominal dollars distributed.
 */
amount: number, } | { "kind": "contribution", 
/**
 * The receiving account id.
 */
account: string, 
/**
 * Employee contribution from cash flow.
 */
employee: number, 
/**
 * Employer contribution landing directly.
 */
employer: number, 
/**
 * How the amounts arose, where a figure alone does not say.
 */
notes: Array<ContributionNote>, } | { "kind": "conversion", 
/**
 * Source account id.
 */
from: string, 
/**
 * Destination account id.
 */
to: string, 
/**
 * Nominal dollars converted.
 */
amount: number, } | { "kind": "withdrawal", 
/**
 * The account drained.
 */
account: string, 
/**
 * Nominal dollars withdrawn.
 */
amount: number, } | { "kind": "surplus", 
/**
 * The account swept into.
 */
account: string, 
/**
 * Nominal dollars swept.
 */
amount: number, };
