// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the runs were made under, and where it is edited.
 */
export type AssumptionRow = { 
/**
 * What it is.
 */
label: string, 
/**
 * What the plan says of it.
 */
value: string, 
/**
 * The domain's page address.
 */
domain: string, 
/**
 * The field it is edited at, where it is one.
 */
field: string | null, };
