// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One projected year across every run.
 */
export type Band = { 
/**
 * The calendar year.
 */
year: number, 
/**
 * Net worth at [`BAND_PERCENTILES`], lowest first.
 */
net_worth: [number, number, number, number, number], 
/**
 * The share of runs not yet short by the year's end.
 */
funded: number, };
