// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Spread } from "./Spread";

/**
 * The market runs' outer and inner bands and their median.
 */
export type BandWords = { 
/**
 * The widest band, drawn lightest.
 */
outer: Spread, 
/**
 * The band within it.
 */
inner: Spread, 
/**
 * The line through their middle.
 */
median: Spread, };
