// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A value in either dollar basis.
 */
export type Bases<T> = { 
/**
 * In today's dollars.
 */
today: T, 
/**
 * In the dollars of each year.
 */
nominal: T, };
