// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a search's best option does better than the plan as it stands, as
 * the Overview says it, in either dollar basis.
 */
export type Better = { 
/**
 * In today's dollars.
 */
today: string, 
/**
 * In the dollars of each year.
 */
nominal: string, };
