// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bases } from "./Bases";
import type { ScaledExpense } from "./ScaledExpense";

/**
 * One ceiling the search found.
 */
export type CeilingOption = { 
/**
 * What the address holds it by: `planned` or `target`.
 */
key: string, 
/**
 * What it was held to: `In 90% of markets`.
 */
held_to: string, 
/**
 * Its flexible spending, change and success, then the plan's figures
 * at it.
 */
figures: Bases<Array<string>>, 
/**
 * Each expense it scales: its name, what the plan states, and what
 * the ceiling makes it.
 */
items: Array<[string, string, string]>, 
/**
 * The amounts it makes of the plan's flexible expenses, as it is
 * taken or written.
 */
expenses: Array<ScaledExpense>, 
/**
 * What is asked before it is taken into the plan searched.
 */
question: string, };
