// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A table cell: what it says, and the number it says where it is one,
 * which is what its column is ordered by.
 */
export type Cell = { 
/**
 * What the cell says.
 */
text: string, 
/**
 * The number it says, where it is one.
 */
number: number | null, 
/**
 * Whether it says what an empty field stands for rather than a value
 * the plan states.
 */
is_unstated: boolean, };
