// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One line of a chart: what it is called and its figure in each year.
 */
export type ChartLine = { 
/**
 * What the chart's key calls it.
 */
label: string, 
/**
 * Each year beside its figure, first to last.
 */
points: Array<[number, number]>, };
