// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A year a chart points out.
 */
export type ChartMark = { 
/**
 * The calendar year.
 */
year: number, 
/**
 * What happens in it.
 */
label: string, };
