// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A chart of the Overview's.
 */
export type Chart = "balances" | "net-worth" | "income-taxes" | "markets";
