// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartLine } from "./ChartLine";
import type { ChartMark } from "./ChartMark";

/**
 * What one of the Overview's charts draws of the plan's own projection.
 */
export type Charted = { 
/**
 * What each treatment the plan holds has, stacked from the bottom in
 * this order.
 */
stacked: Array<ChartLine>, 
/**
 * The lines drawn over them.
 */
lines: Array<ChartLine>, 
/**
 * The years each earner's salary ends.
 */
marks: Array<ChartMark>, };
