// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One year's charted figures.
 */
export type ChartYear = { 
/**
 * The calendar year.
 */
year: number, 
/**
 * What each treatment class holds.
 */
classes: Array<number>, 
/**
 * Everything the household holds.
 */
net_worth: number, 
/**
 * Everything it earned.
 */
income: number, 
/**
 * Everything it paid in tax.
 */
taxes: number, };
