// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartMark } from "./ChartMark";
import type { ChartYear } from "./ChartYear";

/**
 * The projection as the Overview charts it.
 */
export type ChartSeries = { 
/**
 * The treatment classes the plan uses, named as a chart keys them, in
 * the order each year's `classes` are.
 */
classes: Array<string>, 
/**
 * Each year, first to last.
 */
years: Array<ChartYear>, 
/**
 * The years each earner's salary ends.
 */
marks: Array<ChartMark>, };
