// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One income claimed at one age.
 */
export type Claim = { 
/**
 * The income's id.
 */
income: string, 
/**
 * The person whose age the claim is at.
 */
owner: string, 
/**
 * The whole age claimed at.
 */
age: number, };
