// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bases } from "./Bases";
import type { ClaimOption } from "./ClaimOption";

/**
 * Every claim age for the household, best first, beside the plan as it
 * stands.
 */
export type ClaimsOptions = { 
/**
 * Each person claimed for, by name, then each figure.
 */
columns: Array<string>, 
/**
 * What the plan's own row is called.
 */
current: string, 
/**
 * The age each claim is at in the plan as it stands, or what an
 * unpaid one says.
 */
current_ages: Array<string>, 
/**
 * The plan's figures as it stands.
 */
baseline: Bases<[number, number, number, number]>, 
/**
 * Every set of claims, best first.
 */
options: Array<ClaimOption>, 
/**
 * The incomes the search made up for people with a record and none,
 * handed back with the claims taken or written.
 */
added: unknown[], 
/**
 * What the best claims do better than the plan, in either basis.
 */
better: Bases<string>, };
