// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bases } from "./Bases";
import type { Claim } from "./Claim";

/**
 * One set of claims the search tried.
 */
export type ClaimOption = { 
/**
 * Its ages joined, as the address holds it: `70-67`.
 */
key: string, 
/**
 * One claim per claimant, in the reply's column order.
 */
claims: Array<Claim>, 
/**
 * The plan's figures under them.
 */
figures: Bases<Array<string>>, 
/**
 * What is asked before they are taken into the plan searched.
 */
question: string, };
