// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Claim } from "./Claim";
import type { ClaimFigures } from "./ClaimFigures";

/**
 * One set of claims the search tried.
 */
export type ClaimOption = { 
/**
 * Its ages joined, as the address holds it: `70-67`.
 */
key: string, 
/**
 * The age each person claims at, in the reply's column order.
 */
ages: Array<number>, 
/**
 * What is taken or written.
 */
claims: Array<Claim>, 
/**
 * The plan's figures under them.
 */
figures: ClaimFigures, 
/**
 * What is asked before they are taken into the plan searched.
 */
question: string, };
