// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Claim } from "./Claim";
import type { Summary } from "./Summary";

/**
 * One set of claims the search tried.
 */
export type ClaimEntry = { 
/**
 * One claim per searched income.
 */
claims: Array<Claim>, 
/**
 * Headline figures under those claims.
 */
summary: Summary, };
