// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the SSA Benefits tool and the Could do better card say of
 * themselves.
 */
export type ClaimWords = { 
/**
 * The People table's columns.
 */
people_columns: [string, string, string, string, string, string], 
/**
 * Before anything is searched.
 */
nothing_searched: string, 
/**
 * Where the household has no one.
 */
nobody: string, 
/**
 * The card's title.
 */
could_do_better: string, 
/**
 * A Roth owner's row where the search is refused.
 */
refused: string, 
/**
 * The card where there is nothing to search.
 */
nothing_to_search: string, };
