// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClaimEntry } from "./ClaimEntry";
import type { Summary } from "./Summary";

/**
 * A claim search, as `optimize claims` and `optimize_claims` reply.
 */
export type ClaimsReply = { 
/**
 * Headline figures with the plan's own claims.
 */
baseline: Summary, 
/**
 * The income ids searched, in the order each candidate's claims hold
 * them.
 */
incomes: Array<string>, 
/**
 * Every candidate, best first: least unfunded spending, then the
 * highest final net worth in today's dollars, then earlier claims.
 */
candidates: Array<ClaimEntry>, };
