// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Better } from "./Better";
import type { ClaimFigures } from "./ClaimFigures";
import type { ClaimOption } from "./ClaimOption";

/**
 * Every claim age for the household, best first, beside the plan as it
 * stands.
 */
export type ClaimsOptions = { 
/**
 * Each person claimed for, by name, then each figure.
 */
columns: Array<string>, 
/**
 * What the plan's own row is called.
 */
current: string, 
/**
 * The age each claim is at in the plan as it stands, or what an
 * unpaid one says.
 */
current_ages: Array<string>, 
/**
 * The plan's figures as it stands.
 */
baseline: ClaimFigures, 
/**
 * Every set of claims, best first.
 */
options: Array<ClaimOption>, 
/**
 * What the best claims do better than the plan, in either basis.
 */
better: Better, };
