// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * End-of-year balances aggregated by treatment class.
 */
export type ClassTotals = { 
/**
 * Taxable: brokerage and cash.
 */
taxable: number, 
/**
 * Tax-deferred.
 */
deferred: number, 
/**
 * Roth.
 */
roth: number, 
/**
 * HSA.
 */
hsa: number, };
