// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricChoice } from "./MetricChoice";

/**
 * What the Compare page says that no plan does.
 */
export type CompareWords = { 
/**
 * What the baseline changes of itself.
 */
the_baseline: string, 
/**
 * What a plan no different from the baseline changes of it.
 */
the_same: string, 
/**
 * A year a plan does not reach.
 */
unreached: string, 
/**
 * Every metric, in the order they are offered.
 */
metrics: Array<MetricChoice>, };
