// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Metric } from "./Metric";

/**
 * What the page shows the plans in.
 */
export type CompareView = { 
/**
 * In the dollars of each year, else today's.
 */
nominal: boolean, 
/**
 * The metric charted and tabled year by year.
 */
metric: Metric, 
/**
 * The year the table's year column is for.
 */
year: number, };
