// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a field is entered.
 */
export type Control = "text" | "money" | "whole" | "flag" | "choice" | "rate" | "share" | "growth" | "trigger" | "presence" | "listed" | "order" | "remainder";
