// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a year's contribution into an account came to be what it is.
 */
export type ContributionNote = { "kind": "share", 
/**
 * The share paid this year, the step applied.
 */
rate: number, 
/**
 * The income id.
 */
of: string, } | { "kind": "maximum" } | { "kind": "match", 
/**
 * The share of the employee's contribution matched.
 */
rate: number, 
/**
 * The share of the income's gross matched up to.
 */
up_to: number, 
/**
 * The income id.
 */
of: string, } | { "kind": "after_tax", 
/**
 * Nominal dollars paid after tax.
 */
amount: number, } | { "kind": "held_to_limit" } | { "kind": "held_to_overall" } | { "kind": "roth_ira_phase_out" } | { "kind": "not_deducted", 
/**
 * Nominal dollars not deducted.
 */
amount: number, };
