// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One labelled amount of a year's income or of what it paid.
 */
export type DetailLine = { 
/**
 * What the amount is.
 */
label: string, 
/**
 * The amount, on the basis asked for.
 */
amount: number, };
