// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One of the plan's editing domains, as its page is named.
 */
export type Domain = { 
/**
 * Its page's address: its title, lower-cased.
 */
slug: string, 
/**
 * What a heading calls it.
 */
title: string, 
/**
 * What it holds, where it holds many items.
 */
purpose: string | null, };
