// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TableColumn } from "./TableColumn";
import type { TableRow } from "./TableRow";

/**
 * A domain's items as its table shows them.
 */
export type DomainTable = { 
/**
 * Each column, in the order its cells are.
 */
columns: Array<TableColumn>, 
/**
 * Each item, in the order asked for.
 */
rows: Array<TableRow>, };
