// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How many runs ended in a bucket.
 */
export type Ending = { 
/**
 * The bucket: "short", or a span of what the runs end with.
 */
label: string, 
/**
 * How many runs ended in it.
 */
count: number, 
/**
 * Whether it holds the runs that fell short.
 */
is_short: boolean, };
