// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An example plan, as a first plan is chosen from them.
 */
export type Example = { 
/**
 * The file it is kept as.
 */
file: string, 
/**
 * The words it is offered under.
 */
words: string, 
/**
 * The plan.
 */
text: string, };
