// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The worst historical start the plan does not survive, as the Overview
 * lists it.
 */
export type FailingStart = { 
/**
 * What the Historical tool keeps its run by.
 */
key: string, 
/**
 * The row: the start, and how many fail.
 */
said: string, };
