// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Control } from "./Control";
import type { Offer } from "./Offer";
import type { TriggerView } from "./TriggerView";

/**
 * One field on show.
 */
export type FieldView = { 
/**
 * The key it is set by.
 */
key: string, 
/**
 * Its place in the list at its key, where it is one row of several.
 */
place: number | null, 
/**
 * What the form calls it.
 */
label: string, 
/**
 * What it means.
 */
help: string, 
/**
 * How it is entered.
 */
control: Control, 
/**
 * What it shows while the keyboard is elsewhere; a pick's value.
 */
text: string, 
/**
 * What it shows while typed into: money as plain digits.
 */
typed: string, 
/**
 * What it shows while entered empty: `Blank is 65`; none where it
 * may not be left empty.
 */
placeholder: string | null, 
/**
 * What it reads as once left empty: `65, the default`.
 */
unstated: string, 
/**
 * The heading it is gathered under with its neighbours, where it is.
 */
group: string | null, 
/**
 * A rate's or a share's number, for its slider.
 */
number: number | null, 
/**
 * Whether a flag or a tick is set.
 */
is_ticked: boolean, 
/**
 * Whether a remainder is less than none or more than the whole.
 */
is_exceeded: boolean, 
/**
 * What a pick offers, a blank first where it may be emptied.
 */
offers: Array<Offer>, 
/**
 * A trigger's kind and operands.
 */
trigger: TriggerView | null, 
/**
 * What the draft's gate finds wrong with it.
 */
issue: string | null, 
/**
 * Why what is entered in it does not yet make a value.
 */
complaint: string | null, };
