// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An option's amounts under the reply's columns past the first, in
 * either dollar basis.
 */
export type Figures = { 
/**
 * In today's dollars.
 */
today: [number, number, number, number, number], 
/**
 * In the dollars of each year.
 */
nominal: [number, number, number, number, number], };
