// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Summary } from "./Summary";

/**
 * Headline figures in either dollar basis.
 */
export type Figures = { 
/**
 * In today's dollars.
 */
today: Summary, 
/**
 * In the dollars of each year.
 */
nominal: Summary, };
