// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DetailLine } from "./DetailLine";

/**
 * One side of a year's money: every amount in one list, what each kind
 * of them comes to, and what they all come to.
 */
export type Funds = { 
/**
 * Each amount, in the order it is read.
 */
lines: Array<DetailLine>, 
/**
 * What the lines of each kind come to, said beneath them as a
 * summary; none where one sum would only repeat the total.
 */
sums: Array<DetailLine>, 
/**
 * The side's total, which the other side's equals.
 */
total: DetailLine, };
