// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoryYear } from "./HistoryYear";

/**
 * One of the year's money panes charted across every year.
 */
export type HistoryChart = { 
/**
 * What it is titled.
 */
title: string, 
/**
 * What its two lines are named.
 */
lines: [string, string], 
/**
 * Each year, first to last.
 */
years: Array<HistoryYear>, };
