// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RunEntry } from "./RunEntry";

/**
 * A Historical search, as `historical` and `plan_historical` reply.
 */
export type HistoricalReply = { 
/**
 * The first start year tried.
 */
from: number, 
/**
 * The last start year tried.
 */
to: number, 
/**
 * Whether histories went on from the record's start past its end.
 */
wrap: boolean, 
/**
 * How many start years ran.
 */
runs: number, 
/**
 * How many succeeded.
 */
successes: number, 
/**
 * The share that succeeded.
 */
success_rate: number, 
/**
 * The plan as planned, then every start year, worst first.
 */
start_years: Array<RunEntry>, };
