// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One year of a history.
 */
export type HistoryYear = { 
/**
 * The calendar year.
 */
year: number, 
/**
 * Its two figures, in the order of the lines.
 */
figures: [number, number], };
