// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A semantic problem found in a plan.
 */
export type Issue = { 
/**
 * TOML-style path of the offending item, e.g. `accounts[2].locked_until`.
 */
path: string, 
/**
 * What is wrong.
 */
message: string, };
