// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Figures } from "./Figures";
import type { LadderYear } from "./LadderYear";

/**
 * One bracket's ladder.
 */
export type LadderOption = { 
/**
 * The bracket's rate, such as 0.22.
 */
rate: number, 
/**
 * The rate as a percent: `22%`.
 */
label: string, 
/**
 * What it converts over the plan, in today's dollars.
 */
converted_today: number, 
/**
 * What it converts over the plan, nominal.
 */
converted_nominal: number, 
/**
 * The plan's figures with the ladder.
 */
figures: Figures, 
/**
 * Its conversions, year by year.
 */
steps: Array<LadderYear>, 
/**
 * What is asked before it is taken into the plan searched.
 */
question: string, };
