// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One year of a ladder: what it converts, and from where.
 */
export type LadderYear = { 
/**
 * The year converted in.
 */
year: number, 
/**
 * The account converted from, by id.
 */
source: string, 
/**
 * The account converted from, by name.
 */
from: string, 
/**
 * Nominal dollars converted.
 */
amount: number, 
/**
 * The ordinary income taxed that year with the ladder, nominal.
 */
taxable: number, 
/**
 * What it converts, in today's dollars.
 */
amount_today: number, 
/**
 * The ordinary income taxed that year, in today's dollars.
 */
taxable_today: number, };
