// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bases } from "./Bases";
import type { LadderOption } from "./LadderOption";

/**
 * Every bracket's ladder, best first, beside the plan as it stands.
 */
export type LaddersReply = { 
/**
 * What an option's columns are called: the bracket, what the plan
 * converts over its life, then each of its figures.
 */
columns: Array<string>, 
/**
 * What a ladder's conversions are tabled under.
 */
conversion_columns: Array<string>, 
/**
 * What the plan's own row is called.
 */
current: string, 
/**
 * The Roth account the ladders fill.
 */
destination: string, 
/**
 * The plan's figures as it stands.
 */
baseline: Bases<[number, number, number, number, number]>, 
/**
 * One option per bracket searched, best first.
 */
brackets: Array<LadderOption>, 
/**
 * What the best ladder does better than the plan, in either basis.
 */
better: Bases<string>, };
