// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Figures } from "./Figures";
import type { LadderOption } from "./LadderOption";

/**
 * Every bracket's ladder, best first, beside the plan as it stands.
 */
export type LaddersReply = { 
/**
 * The Roth account the ladders fill.
 */
destination: string, 
/**
 * The plan's figures as it stands.
 */
baseline: Figures, 
/**
 * One option per bracket searched, best first.
 */
brackets: Array<LadderOption>, };
