// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the tool says of itself, beside what a search replies.
 */
export type LadderWords = { 
/**
 * While no Roth account is named to convert to.
 */
pick_destination: string, 
/**
 * Where the constraints leave no bracket to fill.
 */
no_bracket: string, 
/**
 * In place of a ladder that converts nothing.
 */
converts_nothing: string, 
/**
 * The column a phone's row shows beside the bracket.
 */
against_plan: string, };
