// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bases } from "./Bases";
import type { LadderYear } from "./LadderYear";

/**
 * One bracket's ladder.
 */
export type LadderOption = { 
/**
 * The bracket's rate, such as 0.22.
 */
rate: number, 
/**
 * The rate as a percent: `22%`.
 */
label: string, 
/**
 * The plan's figures with the ladder.
 */
figures: Bases<Array<string>>, 
/**
 * Its conversions, year by year.
 */
steps: Array<LadderYear>, 
/**
 * What is asked before it is taken into the plan searched.
 */
question: string, };
