// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Marks } from "./Marks";

/**
 * One year of the Ledger's table.
 */
export type LedgerRow = { 
/**
 * The calendar year.
 */
year: number, 
/**
 * The ages reached in it.
 */
ages: string, 
/**
 * What sets it apart in the list of years.
 */
marks: Marks, 
/**
 * Its figures, in the order of their headers.
 */
figures: Array<string>, 
/**
 * Whether the year could not pay for everything.
 */
is_exceeded: boolean, };
