// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LedgerColumn } from "./LedgerColumn";
import type { LedgerRow } from "./LedgerRow";

/**
 * Every projected year as the Ledger's table shows it.
 */
export type Ledger = { 
/**
 * Each column, in the order its cells are: the year, the ages, and
 * then each figure.
 */
columns: Array<LedgerColumn>, 
/**
 * Each year, first to last.
 */
rows: Array<LedgerRow>, };
