// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LedgerRow } from "./LedgerRow";

/**
 * Every projected year as the Ledger's table shows it.
 */
export type Ledger = { 
/**
 * What heads the year and the ages reached in it.
 */
text_headers: [string, string], 
/**
 * What heads each figure: the `leading` every set opens with, then
 * the set's own, then net worth.
 */
figure_headers: Array<string>, 
/**
 * How many figures every set opens with.
 */
leading: number, 
/**
 * Each year, first to last.
 */
rows: Array<LedgerRow>, };
