// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LedgerRow } from "./LedgerRow";
import type { TableColumn } from "./TableColumn";

/**
 * Every projected year as the Ledger's table shows it.
 */
export type Ledger = { 
/**
 * Each column, in the order its cells are.
 */
columns: Array<TableColumn>, 
/**
 * Each year, first to last.
 */
rows: Array<LedgerRow>, };
