// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One year of the Ledger's table.
 */
export type LedgerRow = { 
/**
 * The calendar year.
 */
year: number, 
/**
 * Its cells, in column order.
 */
cells: Array<string>, 
/**
 * Whether the year could not pay for everything.
 */
is_exceeded: boolean, };
