// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the market tools say that no search does.
 */
export type MarketWords = { 
/**
 * What the runs say before their first search answers.
 */
nothing_searched: string, };
