// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssumptionRow } from "./AssumptionRow";
import type { Band } from "./Band";
import type { Ending } from "./Ending";
import type { FailingStart } from "./FailingStart";
import type { RunRow } from "./RunRow";
import type { Table } from "./Table";
import type { Zone } from "./Zone";

/**
 * A market tool's runs, as its page shows them.
 */
export type MarketRuns = { 
/**
 * How the plan fared: "Money lasts in 87% of 1,000 markets".
 */
verdict: string, 
/**
 * The share of runs it survives and of how many: "87% of 1,000
 * markets".
 */
success: string, 
/**
 * The zone its share falls in.
 */
zone: Zone, 
/**
 * The share of runs that succeeded.
 */
success_rate: number, 
/**
 * How many runs there were.
 */
count: number, 
/**
 * The runs table's columns.
 */
columns: [string, string, string], 
/**
 * The plan in its own market, then each run singled out.
 */
runs: Array<RunRow>, 
/**
 * Net worth year by year across the runs.
 */
bands: Array<Band>, 
/**
 * Net worth at each percentile year by year, where the tool shows it.
 */
by_year: Table | null, 
/**
 * How many runs end in each bucket, the short first.
 */
endings: Array<Ending>, 
/**
 * What the runs are made under, and where each is edited.
 */
assumptions: Array<AssumptionRow>, 
/**
 * The worst start the plan does not survive, where the runs are
 * historical and one fails.
 */
failing: FailingStart | null, };
