// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What sets a year apart in a list of them.
 */
export type Marks = { 
/**
 * A milestone of the plan falls in it.
 */
is_milestone: boolean, 
/**
 * It has a warning.
 */
has_warning: boolean, };
