// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A projected quantity comparable year by year, kept as its kebab-case
 * name.
 */
export type Metric = "net-worth" | "income" | "expenses" | "taxes" | "withdrawals" | "conversions" | "magi" | "unfunded";
