// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Metric } from "./Metric";

/**
 * A metric the page offers.
 */
export type MetricChoice = { 
/**
 * What the address keeps it by.
 */
key: Metric, 
/**
 * What it is called.
 */
title: string, };
