// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Band } from "./Band";
import type { RunEntry } from "./RunEntry";

/**
 * A Monte Carlo search, as `monte-carlo` and `plan_monte_carlo` reply.
 */
export type MonteCarloReply = { 
/**
 * "assumptions" or "history".
 */
draw: string, 
/**
 * The seed the markets were drawn from.
 */
seed: number, 
/**
 * How many markets ran.
 */
runs: number, 
/**
 * How many succeeded.
 */
successes: number, 
/**
 * The share that succeeded.
 */
success_rate: number, 
/**
 * The plan as planned, then the markets singled out, best first.
 */
markets: Array<RunEntry>, 
/**
 * Net worth year by year across the markets.
 */
bands: Array<Band>, };
