// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Display names by id, one map per list, since ids are unique only within
 * their list.
 */
export type Names = { 
/**
 * The household's people.
 */
people: { [key in string]: string }, 
/**
 * The accounts.
 */
accounts: { [key in string]: string }, };
