// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The plan the answers made, and the name it is offered under.
 */
export type NewPlanMade = { 
/**
 * The plan as canonical TOML.
 */
text: string, 
/**
 * A file name for it, without its extension: its first person's name.
 */
name: string, };
