// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonAction } from "./PersonAction";

/**
 * An action offered on a person.
 */
export type OfferedAction = { 
/**
 * Which.
 */
action: PersonAction, 
/**
 * What it is called.
 */
label: string, };
