// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One thing a select offers: the value the file keeps, and the words
 * shown for it.
 */
export type Offer = { 
/**
 * What the file keeps.
 */
value: string, 
/**
 * The words shown for it.
 */
label: string, };
