// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PersonAction } from "./PersonAction";

/**
 * An action offered on a person.
 */
export type OfferedAction = { 
/**
 * Which.
 */
action: PersonAction, 
/**
 * What it is called.
 */
label: string, 
/**
 * What is asked before it is done, where it drops something.
 */
question: string | null, 
/**
 * The answer that does it, where it is asked about.
 */
answer: string | null, };
