// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Written } from "./Written";

/**
 * A document that did not open: why, in a line, and the file that failed
 * where the failure is in its text.
 */
export type OpenFailure = { 
/**
 * The failure in a line: the file by name, where, and why.
 */
headline: string, 
/**
 * The file that failed, where the failure is in its text.
 */
written: Written | null, };
