// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A document that did not open: the file that failed, said in a line,
 * and, where the failure is in its text, where.
 */
export type OpenFailure = { 
/**
 * The file that failed, as the page's files are named: the one opened
 * or a base in its chain.
 */
file: string, 
/**
 * The failure in a line: the file by name, where, and why.
 */
headline: string, 
/**
 * The line it is on, from 1; `null` where it is not in the text.
 */
line: number | null, 
/**
 * The column on that line, from 1, in characters.
 */
column: number | null, 
/**
 * The failing file's text, where the failure is in it.
 */
text: string | null, };
