// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Offer } from "./Offer";

/**
 * One operand of a trigger's sentence.
 */
export type OperandView = { 
/**
 * The part it is set by.
 */
key: string, 
/**
 * The words before it.
 */
before: string, 
/**
 * The words after it.
 */
after: string, 
/**
 * What it means.
 */
help: string, 
/**
 * What it holds; a pick's value.
 */
text: string, 
/**
 * What it offers, where it is picked from the plan's ids.
 */
offers: Array<Offer> | null, };
