// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bases } from "./Bases";
import type { OrderOption } from "./OrderOption";

/**
 * Every order the plan's classes can be drained in, best first, beside the
 * plan as it stands.
 */
export type OrderOptions = { 
/**
 * The order, then what an option ends with against the plan, then each
 * figure.
 */
columns: Array<string>, 
/**
 * What the plan's own row is called.
 */
current: string, 
/**
 * The plan's figures as it stands.
 */
baseline: Bases<Array<string>>, 
/**
 * One option for each distinct outcome, best first.
 */
options: Array<OrderOption>, 
/**
 * What the best order does better than the plan, in either basis.
 */
better: Bases<string>, };
