// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bases } from "./Bases";
import type { TreatmentClass } from "./TreatmentClass";

/**
 * One order the search tried.
 */
export type OrderOption = { 
/**
 * Its classes joined, as the address holds it: `taxable-roth-deferred`.
 */
key: string, 
/**
 * The classes, first drained first.
 */
order: Array<TreatmentClass>, 
/**
 * The order in words.
 */
said: string, 
/**
 * The plan's figures under it.
 */
figures: Bases<Array<string>>, 
/**
 * What is asked before it is taken into the plan searched.
 */
question: string, };
