// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the Withdrawal Order tool says of itself.
 */
export type OrderWords = { 
/**
 * What the tool is for, in a line.
 */
about: string, 
/**
 * Before anything is searched.
 */
nothing_searched: string, 
/**
 * The column a phone's row shows beside the order.
 */
against_plan: string, };
