// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverviewRow } from "./OverviewRow";
import type { Shortfall } from "./Shortfall";

/**
 * What the Overview says of a projection, in one dollar basis.
 */
export type OverviewView = { 
/**
 * How long the money lasts, where the shortfall says by how much:
 * "Never short", "Through 2041", "Short from the start".
 */
money_lasts: string, 
/**
 * Where it runs short; `null` where it never does.
 */
shortfall: Shortfall | null, 
/**
 * Net worth at the end.
 */
ends_with: string, 
/**
 * Every year's taxes together.
 */
lifetime_taxes: string, 
/**
 * What needs attention in the projection, what has no year first.
 */
attention: Array<OverviewRow>, 
/**
 * The plan's milestones, earliest first.
 */
milestones: Array<OverviewRow>, };
