// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Place } from "./Place";

/**
 * A row of Needs attention or Milestones.
 */
export type OverviewRow = { 
/**
 * What it says, without its year.
 */
text: string, 
/**
 * The year it is about, where it is about one.
 */
year: number | null, 
/**
 * The item behind it, where it has one.
 */
place: Place | null, };
