// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssumptionRow } from "./AssumptionRow";
import type { OverviewRow } from "./OverviewRow";
import type { OverviewTotal } from "./OverviewTotal";
import type { Shortfall } from "./Shortfall";

/**
 * What the Overview says of a projection, in one dollar basis.
 */
export type OverviewView = { 
/**
 * How long the money lasts, where the shortfall says by how much:
 * "Never short", "Through 2041", "Short from the start".
 */
money_lasts: string, 
/**
 * Where it runs short; `null` where it never does.
 */
shortfall: Shortfall | null, 
/**
 * The least the household holds once the last salary ends, and when.
 */
low_point: string, 
/**
 * Net worth at the end.
 */
ends_with: string, 
/**
 * What needs attention in the projection, what has no year first.
 */
attention: Array<OverviewRow>, 
/**
 * The plan's milestones, earliest first.
 */
milestones: Array<OverviewRow>, 
/**
 * What the years add up to.
 */
totals: Array<OverviewTotal>, 
/**
 * What the projection hangs from, each at the field it is edited at.
 */
rests_on: Array<AssumptionRow>, };
