// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OverviewRow } from "./OverviewRow";

/**
 * What the Overview says of a projection, in one dollar basis.
 */
export type OverviewView = { 
/**
 * How long the money lasts: "Never short", "Short $772k from 2042".
 */
money_lasts: string, 
/**
 * The first year it runs short; `null` where it never does.
 */
short_year: number | null, 
/**
 * That year and what the money cannot cover, as a sentence.
 */
runs_short: string | null, 
/**
 * Net worth at the end.
 */
ends_with: string, 
/**
 * Every year's taxes together.
 */
lifetime_taxes: string, 
/**
 * What needs attention in the projection, what has no year first.
 */
attention: Array<OverviewRow>, 
/**
 * The plan's milestones, earliest first.
 */
milestones: Array<OverviewRow>, };
