// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TotalLeads } from "./TotalLeads";

/**
 * A lifetime total: what it sums, what it is made of and where it leads.
 */
export type OverviewTotal = { 
/**
 * What it totals.
 */
label: string, 
/**
 * The total, compact.
 */
amount: string, 
/**
 * What it is made of; empty where it is nothing.
 */
made_of: string, 
/**
 * Where it leads, where it leads anywhere.
 */
leads: TotalLeads | null, };
