// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OfferedAction } from "./OfferedAction";

/**
 * A person as the People table shows them.
 */
export type PersonRow = { 
/**
 * Their id, what `?held` names them by.
 */
id: string, 
/**
 * Their name, which an edit checks they still have.
 */
name: string, 
/**
 * The cells under the table's columns.
 */
cells: Array<string>, 
/**
 * What can be done for them.
 */
actions: Array<OfferedAction>, };
