// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What can be done for a person on the SSA Benefits page.
 */
export type PersonAction = "import" | "fill-career" | "compute-benefit" | "hold" | "let-vary" | "clear-record" | "remove-benefit";
