// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Place } from "./Place";

/**
 * An issue beside where it is in the plan, in the forms' words.
 */
export type PlacedIssue = { 
/**
 * The plan path it is about, such as `accounts[2].locked_until`.
 */
path: string, 
/**
 * What is wrong, as the engine says it.
 */
message: string, 
/**
 * The domain, the item by its display name and the field's label,
 * then the message; the engine's own words where no domain holds it.
 */
words: string, 
/**
 * Where a form edits what it is about; `null` where none does.
 */
place: Place | null, };
