// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where in the plan's pages an issue is.
 */
export type Place = { 
/**
 * The domain's page address.
 */
domain: string, 
/**
 * The item, where the domain holds many.
 */
index: number | null, 
/**
 * The key of the field, where a form has one for it.
 */
field: string | null, };
