// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { YearRow } from "./YearRow";

/**
 * One projected plan: a row per calendar year.
 */
export type Projection = { 
/**
 * Rows from the plan's start year through the horizon.
 */
years: Array<YearRow>, };
