// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A row of an item read out: a field's label and what it holds.
 */
export type ReadRow = { 
/**
 * What the form calls the field.
 */
label: string, 
/**
 * What it holds, in the form's words.
 */
text: string, 
/**
 * Whether that is what an empty field stands for rather than a value
 * the plan states.
 */
is_unstated: boolean, };
