// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Roth owner, and the account the Overview searches a ladder into.
 */
export type RothOwner = { 
/**
 * Their name.
 */
name: string, 
/**
 * Their first Roth account, by id.
 */
destination: string, };
