// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One run as the replies show it.
 */
export type RunEntry = { 
/**
 * What the run is: "as planned", a percentile, "worst", or a start
 * year.
 */
market: string, 
/**
 * The Monte Carlo trial it was.
 */
trial: number | null, 
/**
 * The historical year it started in.
 */
start: number | null, 
/**
 * Net worth at the horizon, today's dollars.
 */
ending: number, 
/**
 * Spending left uncovered over the run, today's dollars.
 */
unfunded: number, 
/**
 * The first year spending went uncovered.
 */
first_short: number | null, 
/**
 * Never short, and leaving at least what the plan asks.
 */
success: boolean, };
