// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A run in the table.
 */
export type RunRow = { 
/**
 * What a highlight is kept by, which the same place keeps after a
 * search again: `planned`, `p90`, `worst`, a start year.
 */
key: string, 
/**
 * The market it went through, as the Ledger's address keeps it;
 * `null` for the plan's own.
 */
market: string | null, 
/**
 * What it shows under each column.
 */
cells: Array<string>, 
/**
 * Its net worth at each year's end, today's dollars.
 */
net_worth: Array<number>, };
