// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A year as every surface says it: what to do, what to watch, and how old
 * everyone is.
 */
export type SaidYear = { 
/**
 * The year.
 */
year: number, 
/**
 * Each person, by display name, and the age they reach in it.
 */
ages: Array<[string, number]>, 
/**
 * Each action as a sentence, its amount nominal.
 */
actions: Array<string>, 
/**
 * What to watch for in the year.
 */
warnings: Array<string>, };
