// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One flexible expense at the ceiling.
 */
export type ScaledExpense = { 
/**
 * The expense's id.
 */
id: string, 
/**
 * Its annual amount at the ceiling, in today's dollars.
 */
amount: number, };
