// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a plan's search through random markets has found so far.
 */
export type Searched = { "kind": "waiting" } | { "kind": "rate", 
/**
 * The share, from 0 to 1.
 */
rate: number, } | { "kind": "failed" };
