// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One step of the new-plan questions.
 */
export type SetupStep = { 
/**
 * How the step is addressed.
 */
slug: string, 
/**
 * What the step is headed.
 */
title: string, 
/**
 * The keys of the fields it asks, in the form's order.
 */
keys: Array<string>, };
