// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The year the money first runs short, said, and the page of what the
 * plan spends.
 */
export type Shortfall = { 
/**
 * The first year it runs short.
 */
year: number, 
/**
 * That year and what the money cannot cover, as a sentence.
 */
said: string, 
/**
 * The Expenses page's address.
 */
expenses: string, };
