// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The column a table is ordered by, and which way.
 */
export type Sort = { column: number, is_descending: boolean, };
