// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bases } from "./Bases";
import type { CeilingOption } from "./CeilingOption";

/**
 * Both ceilings, beside the plan as it stands.
 */
export type SpendingOptions = { 
/**
 * What a ceiling was held to, its flexible spending, change and
 * success, then each figure.
 */
columns: Array<string>, 
/**
 * What the plan's own row is called.
 */
current: string, 
/**
 * The plan's cells as it stands.
 */
baseline: Bases<Array<string>>, 
/**
 * The ceiling in the plan's own market, then the one at the target.
 */
options: Array<CeilingOption>, 
/**
 * The key of the ceiling highlighted where the address names none.
 */
leading: string, };
