// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the Spending Ceiling tool says of itself.
 */
export type SpendingWords = { 
/**
 * What the tool is for, in a line.
 */
about: string, 
/**
 * Before anything is searched.
 */
nothing_searched: string, 
/**
 * The columns a ceiling's expenses are tabled under.
 */
item_columns: [string, string, string], };
