// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A band of the market runs' spread, or their median: what it is called,
 * and the places in [`BAND_PERCENTILES`] it lies between, one place twice
 * for the median.
 */
export type Spread = { 
/**
 * What a chart's key calls it.
 */
label: string, 
/**
 * The place of the percentile below it.
 */
low: number, 
/**
 * The place of the one above it.
 */
high: number, };
