// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Headline figures aggregated over a whole projection.
 */
export type Summary = { 
/**
 * Net worth at the horizon.
 */
final_net_worth: number, 
/**
 * Highest year-end net worth reached.
 */
peak_net_worth: number, 
/**
 * The year the peak occurs; the first such year on ties.
 */
peak_year: number, 
/**
 * Total taxes assessed across the projection.
 */
lifetime_taxes: number, 
/**
 * Total Roth conversions executed.
 */
lifetime_conversions: number, 
/**
 * Total spending the accounts could not cover.
 */
lifetime_unfunded: number, 
/**
 * Total Medicare surcharges and cliff costs.
 */
lifetime_medicare: number, 
/**
 * First year with an uncovered shortfall; `None` when fully funded.
 */
first_unfunded_year: number | null, 
/**
 * Deferred-class balance at the horizon.
 */
final_deferred: number, };
