// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Summary } from "./Summary";
import type { SweepEntry } from "./SweepEntry";

/**
 * A bracket sweep, as `optimize conversions` and
 * `sweep_conversion_brackets` reply.
 */
export type SweepReply = { 
/**
 * The plan without any ladder.
 */
baseline: Summary, 
/**
 * One entry per fillable bracket, best first: the least left unfunded,
 * then the most left at the end.
 */
brackets: Array<SweepEntry>, };
