// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Summary } from "./Summary";

/**
 * One bracket of a sweep.
 */
export type SweepEntry = { 
/**
 * The bracket's rate (e.g. 0.22).
 */
bracket_rate: number, 
/**
 * The ladder's total, on the reply's dollar basis.
 */
total_converted: number, 
/**
 * Headline figures with the ladder applied.
 */
optimized: Summary, };
