// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Something the tables can be shown for, by the key the view names it.
 */
export type TablesChoice = { 
/**
 * What the view names it by.
 */
key: string, 
/**
 * What it is called.
 */
title: string, };
