// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which tables are asked for: a year, and a status and state other than
 * the plan's where one is named.
 */
export type TablesView = { 
/**
 * The year the tables are for.
 */
year: number, 
/**
 * A filing status as the plan file spells it; the plan's where none.
 */
status?: string, 
/**
 * A state's lowercase code; the one the plan lives in that year where
 * none.
 */
state?: string, };
