// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cell } from "./Cell";

/**
 * One item of a domain's table.
 */
export type TableRow = { 
/**
 * Where the item sits in the plan, whatever order the table shows.
 */
index: number, 
/**
 * What the item is called: what removing it names it by.
 */
name: string, 
/**
 * Its cells, in column order.
 */
cells: Array<Cell>, };
