// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One column of a domain's table.
 */
export type TableColumn = { 
/**
 * What heads it.
 */
header: string, 
/**
 * Whether it holds numbers, which line up on the right.
 */
is_numeric: boolean, };
