// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A table of text.
 */
export type Table = { 
/**
 * Its columns.
 */
columns: Array<string>, 
/**
 * Its rows.
 */
rows: Array<Array<string>>, };
