// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Taxes assessed for one year.
 */
export type Taxes = { 
/**
 * Tax on ordinary income.
 */
ordinary: number, 
/**
 * Tax on long-term capital gains.
 */
ltcg: number, 
/**
 * Early-withdrawal penalties.
 */
penalty: number, 
/**
 * Income tax of the state lived in that year.
 */
state: number, 
/**
 * The taxable portion of Social Security benefits (informational).
 */
taxable_social_security: number, 
/**
 * Ordinary taxable income after the standard deduction, floored at
 * zero (informational; what the bracket walk was fed).
 */
ordinary_taxable: number, 
/**
 * MAGI proxy - ordinary income plus gains plus taxable Social
 * Security (informational; drives IRMAA lookback and cliffs).
 */
magi: number, 
/**
 * Ordinary, gains and state tax plus penalties.
 */
total: number, };
