// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One table of the year's: a title, its columns and its rows, or a note
 * saying why it has none.
 */
export type TaxSection = { 
/**
 * What the table holds.
 */
title: string, 
/**
 * Its column headers.
 */
columns: Array<string>, 
/**
 * Its rows, each a cell per column.
 */
rows: Array<Array<string>>, 
/**
 * Why it has no rows, where it has none.
 */
note: string | null, };
