// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Place } from "./Place";

/**
 * Where a lifetime total leads.
 */
export type TotalLeads = { "place": Place } | { "tool": string } | { "year": number };
