// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tax treatment classes, also the vocabulary of the withdrawal order.
 */
export type TreatmentClass = "taxable" | "deferred" | "roth" | "hsa";
