// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Offer } from "./Offer";
import type { OperandView } from "./OperandView";

/**
 * A trigger as its sentence reads.
 */
export type TriggerView = { 
/**
 * The kind chosen, as the file spells it; blank where none is.
 */
basis: string, 
/**
 * Every kind, a blank first.
 */
bases: Array<Offer>, 
/**
 * The operands the kind has a use for, in the sentence's order.
 */
operands: Array<OperandView>, };
