// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bases } from "./Bases";

/**
 * What the Overview, the Ledger and Compare call what they show.
 */
export type ViewWords = { 
/**
 * The dollars figures are shown in.
 */
basis: Bases<string>, 
/**
 * The year's flows through each account.
 */
flows: string, 
/**
 * The flows table's headers.
 */
flow_headers: [string, string, string, string, string, string], 
/**
 * The year's income beside what it paid.
 */
income_and_tax: string, 
/**
 * The balances chart.
 */
balances_chart: string, 
/**
 * The net worth chart.
 */
net_worth_chart: string, 
/**
 * The income chart.
 */
income_chart: string, };
