// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bases } from "./Bases";
import type { Chart } from "./Chart";

/**
 * What the Overview, the Ledger and Compare call what they show.
 */
export type ViewWords = { 
/**
 * The dollars figures are shown in.
 */
basis: Bases<string>, 
/**
 * The year's flows through each account.
 */
flows: string, 
/**
 * The flows table's headers, each beside whether its column holds figures.
 */
flow_headers: [[string, boolean], [string, boolean], [string, boolean], [string, boolean], [string, boolean], [string, boolean]], 
/**
 * The year's income beside what it paid.
 */
income_and_tax: string, 
/**
 * What a year has the household do.
 */
to_do: string, 
/**
 * The Overview's charts in the order they are turned through, each
 * beside its title.
 */
charts: Array<[Chart, string]>, 
/**
 * The Overview's strip: how long the money lasts, how surely, the
 * least it holds once it stops earning, and what it ends with.
 */
strip: [string, string, string, string], 
/**
 * The Overview's lifetime totals.
 */
over_the_plan: string, 
/**
 * The Overview's assumptions.
 */
rests_on: string, 
/**
 * What is said of the figures while the draft has issues.
 */
stale: string, 
/**
 * The Overview's list of what needs attention.
 */
attention: string, 
/**
 * What it says where nothing does.
 */
nothing_wanting: string, 
/**
 * The Overview's list of the plan's milestones.
 */
milestones: string, 
/**
 * What a year with nothing to do says.
 */
nothing_scheduled: string, };
