// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A file as written, and the line a failure is on.
 */
export type Written = { 
/**
 * The file, as the page's files are named: the one opened or a base
 * in its chain.
 */
file: string, 
/**
 * Its text.
 */
text: string, 
/**
 * The line the failure is on, from 1, where the error knows.
 */
line: number | null, };
