// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountFlows } from "./AccountFlows";
import type { DetailLine } from "./DetailLine";
import type { Funds } from "./Funds";

/**
 * What the Ledger says of one year.
 */
export type Year = { 
/**
 * The calendar year.
 */
year: number, 
/**
 * The age each person reaches in it: "Jordan turns 67 · Alex turns 63".
 */
ages: string, 
/**
 * The plan's milestones that fall in it.
 */
milestones: Array<string>, 
/**
 * What it has the household do, each action a sentence; that there is
 * nothing, where there is not.
 */
to_do: Array<string>, 
/**
 * What to watch in it.
 */
warnings: Array<string>, 
/**
 * What the plan has paid, converted and drawn through it, each beside
 * its lifetime total; none where every total is nothing.
 */
so_far: string | null, 
/**
 * Each account it touches, from its open to its close.
 */
flows: Array<AccountFlows>, 
/**
 * Every account as one, where there are several.
 */
all_accounts: AccountFlows | null, 
/**
 * What it lived on.
 */
money_in: Funds, 
/**
 * Where that went.
 */
money_out: Funds, 
/**
 * What it paid of each kind of tax, and all of it.
 */
tax: Array<DetailLine>, 
/**
 * The room under the top of the federal bracket its taxable income
 * reaches; none for a market run.
 */
bracket: DetailLine | null, 
/**
 * What its tax was worked out from.
 */
picture: Array<DetailLine>, };
