// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A plan's metric in one year.
 */
export type YearFigure = { 
/**
 * The calendar year.
 */
year: number, 
/**
 * The amount, or its difference from the baseline's.
 */
amount: number, 
/**
 * The amount as the table says it.
 */
figure: string, };
