// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountFlows } from "./AccountFlows";
import type { DetailLine } from "./DetailLine";

/**
 * One year beside the Ledger's table.
 */
export type YearDetail = { 
/**
 * Each account the year touches, from its open to its close.
 */
flows: Array<AccountFlows>, 
/**
 * The year's income by source.
 */
income: Array<DetailLine>, 
/**
 * Its spending and what it paid besides.
 */
paid: Array<DetailLine>, 
/**
 * What needs attention, on the same basis.
 */
warnings: Array<string>, };
