// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Offer } from "./Offer";
import type { TaxSection } from "./TaxSection";

/**
 * A year's tables for a status and a state, and the others that can be
 * asked for.
 */
export type YearTables = { 
/**
 * The year they are for.
 */
year: number, 
/**
 * The filing status shown, as the view names it.
 */
status: string, 
/**
 * The state shown, where there is one.
 */
state: string | null, 
/**
 * Every filing status.
 */
statuses: Array<Offer>, 
/**
 * Every state the year's tables model.
 */
states: Array<Offer>, 
/**
 * The tables, federal first.
 */
sections: Array<TaxSection>, 
/**
 * What the tables are, said once above them.
 */
about: string, 
/**
 * What the filing status is picked under.
 */
status_pick: string, 
/**
 * What the state is picked under.
 */
state_pick: string, 
/**
 * The plan's own filing status, as a pick offers it.
 */
own_status: string, 
/**
 * Where the plan lives in the year, as a pick offers it.
 */
own_state: string, };
