// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { ClassTotals } from "./ClassTotals";
import type { Taxes } from "./Taxes";

/**
 * One projected calendar year, in nominal dollars.
 */
export type YearRow = { 
/**
 * The calendar year.
 */
year: number, 
/**
 * Age each person reaches during the year, by person id.
 */
ages: { [key in string]: number }, 
/**
 * Cumulative inflation factor since plan start; nominal ÷ this = today's
 * dollars.
 */
deflator: number, 
/**
 * Gross income by source label, Social Security included.
 */
income: { [key in string]: number }, 
/**
 * Sum of the income map.
 */
total_income: number, 
/**
 * Spending for the year.
 */
expenses: number, 
/**
 * Medicare surcharges and crossed-cliff costs spent this year.
 */
medicare: number, 
/**
 * Employee contributions paid from cash flow.
 */
contributions_employee: number, 
/**
 * Employer contributions landing in accounts.
 */
contributions_employer: number, 
/**
 * Required minimum distributions taken.
 */
rmds: number, 
/**
 * Roth conversions executed.
 */
conversions: number, 
/**
 * Money withdrawn per account id (RMDs included).
 */
withdrawals: { [key in string]: number }, 
/**
 * The year's growth per account id, on what the account opened with;
 * an account that grew nothing is left out.
 */
growth: { [key in string]: number }, 
/**
 * What was executed, in execution order; funding withdrawals, then the
 * surplus swept, last.
 */
actions: Array<Action>, 
/**
 * The year's taxes.
 */
taxes: Taxes, 
/**
 * Unspent income swept to the surplus account.
 */
surplus: number, 
/**
 * Spending the accounts could not cover.
 */
unfunded: number, 
/**
 * End-of-year balance per account id.
 */
balances: { [key in string]: number }, 
/**
 * End-of-year balances by treatment class.
 */
class_totals: ClassTotals, 
/**
 * Sum of all end-of-year balances.
 */
net_worth: number, };
