// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountFlows } from "./AccountFlows";
import type { DetailLine } from "./DetailLine";
import type { Funds } from "./Funds";

/**
 * What the Ledger says of one year.
 */
export type Year = { 
/**
 * The calendar year.
 */
year: number, 
/**
 * The year, the run it is of, the age each person reaches in it and
 * the dollars it is said in: "2042 · Jordan turns 67 · today's
 * dollars".
 */
title: string, 
/**
 * The plan's milestones that fall in it.
 */
milestones: Array<string>, 
/**
 * What it has the household do, each action a sentence; that there is
 * nothing, where there is not.
 */
to_do: Array<string>, 
/**
 * What to watch in it.
 */
warnings: Array<string>, 
/**
 * What the plan has paid, converted and drawn through it, each beside
 * its lifetime total; none where every total is nothing.
 */
so_far: string | null, 
/**
 * Each account it touches, from its open to its close, and then every
 * account as one where there are several.
 */
flows: Array<AccountFlows>, 
/**
 * What it lived on.
 */
money_in: Funds, 
/**
 * Where that went.
 */
money_out: Funds, 
/**
 * What it paid of each kind of tax, and all of it.
 */
tax: Array<DetailLine>, 
/**
 * What its tax was worked out from, led by the room under the top of
 * the federal bracket its taxable income reaches; a market run says
 * no bracket.
 */
worked_from: Array<DetailLine>, };
